version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env
  
  backend:
    container_name: backend_foodgram
    image: vasilevvladv22/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/foodgram_backend/static/
      - media_value:/foodgram_backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend_foodgram
    image: vasilevvladv22/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: nginx_foodgram
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
