version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  backend:
    container_name: backend_foodgram
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    ports:
      - "90:8000"
    restart: always
    volumes:
      - media_value:/foodgram_backend/media/
      - static_value:/foodgram_backend/static/
 
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
volumes:
  static_value:
  media_value: