# Generated by Django 4.0.4 on 2022-07-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipeingredientamount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
