# Generated by Django 3.2.13 on 2022-07-11 15:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_table_alter_recipe_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ff0000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет HEX-код'),
        ),
    ]
